### ISSUE TITLE
Add documentation for usage with AWS OpsWorks

### ISSUE THREAD

**Issue by estahn** [zanui/chef-thumbor#2]

**Comment by yogin** [comment]
I would love to know how you'd go about this since the nginx cookbook will conflict with the cookbook from OpsWorks.

I'm trying to set it up, so far, I've disabled the proxy setup (nginx), and thinking of creating a new recipe for opsworks's version of nginx.

But if you already have recipe for this, it would be much appreciated :)

**Comment by estahn** [comment]
@yogin I'll have a look today. I was unaware that OpsWorks has it's own Nginx Cookbook. In the meantime you can have a look at our wrapper repository which contains all cookbooks: https://github.com/zanui/thumbor-cookbooks ... This is working with OpsWorks and we're using it for production.

**Comment by yogin** [comment]
I got it to work last night, I created a new recipe for OpsWork's version of NGiNX, it's pretty much just a mix of both recipes:

```ruby
package "nginx"

directory node[:nginx][:dir] do
  owner 'root'
  group 'root'
  mode '0755'
end

directory node[:nginx][:log_dir] do
  mode 0755
  owner node[:nginx][:user]
  action :create
end

%w{sites-available sites-enabled conf.d}.each do |dir|
  directory File.join(node[:nginx][:dir], dir) do
    owner 'root'
    group 'root'
    mode '0755'
  end
end

%w{nxensite nxdissite}.each do |nxscript|
  template "/usr/sbin/#{nxscript}" do
    source "#{nxscript}.erb"
    mode 0755
    owner "root"
    group "root"
  end
end

template "nginx.conf" do
  path "#{node[:nginx][:dir]}/nginx.conf"
  source "nginx.conf.erb"
  owner "root"
  group "root"
  mode 0644
end

# nginx proxy cache location
directory node['thumbor']['nginx']['proxy_cache']['path'] do
  owner node['nginx']['user']
  mode '0700'
  action :create
  recursive true
  only_if { node['thumbor']['nginx']['proxy_cache']['enabled'] }
end

# nginx thumbor vhost configuration file
template "#{node[:nginx][:dir]}/sites-available/default" do
  source 'thumbor-site.erb'
  owner 'root'
  group 'root'
  mode '0644'
  variables(
    if node['thumbor']['nginx']['vhost']['variables'].empty?
      { workers: node['thumbor']['workers'],
        base_port: node['thumbor']['base_port'],
        listen_address: node['thumbor']['listen_address'],
        server_port: node['thumbor']['nginx']['port'],
        server_name: node['thumbor']['nginx']['server_name'],
        client_max_body_size: node['thumbor']['nginx']['client_max_body_size'],
        proxy_cache_valid: node['thumbor']['nginx']['proxy_cache']['valid'],
        proxy_read_timeout: node['thumbor']['nginx']['proxy_read_timeout'],
        proxy_cache_enabled: node['thumbor']['nginx']['proxy_cache']['enabled'],
        proxy_cache_path: node['thumbor']['nginx']['proxy_cache']['path'],
        proxy_cache_key_zone: node['thumbor']['nginx']['proxy_cache']['key_zone']
      }
    else
      node['thumbor']['nginx']['vhost']['variables']
    end
  )
end

include_recipe "nginx::service"

service "nginx" do
  action [ :enable, :start ]
end
```

Here it refers to the template `thumbor-site.erb` but it's the same as the one in your recipe

**Comment by yogin** [comment]
Unrelated to this, I tried enabling the nginx proxy settings that you have, but NGiNX was just returning 404s. I didn't have time to look deeper yet, so I disabled it for now. Not sure if it's something due to the different NGiNX packages, or other misconfiguration

**Comment by yogin** [comment]
And for reference, this is the cookbook OpsWorks uses for NGiNX:
https://github.com/aws/opsworks-cookbooks/tree/release-chef-11.10/nginx

**Comment by estahn** [comment]
@yogin I'm not sure what i'm doing different but it's working fine for me. What OS and Chef version do you use?

**Comment by estahn** [comment]
@yogin Please find the documentation on how i set up thumbor on OpsWorks here:
https://github.com/zanui/chef-thumbor/wiki/thumbor-Stack-on-AWS-OpsWorks-in-10-minutes

I didn't use a wrapper cookbook as it doesn't seem necessary anymore.

**Comment by estahn** [comment]
[thumbor Stack on AWS OpsWorks in 10 minutes]

**Comment by yogin** [comment]
Nice, good job on that write up!

It probably works fine here because your Thumbor stack only has a single custom app layer, and none of OpsWorks' setup and configure recipes used in the custom layer reference NGiNX.

In my current stack, the Thumbor layer (a custom app) is one of several layers. One of these other layers include a rails app, so OpsWorks will setup NGiNX for you, using it's own cookbook.

Since all layers in the stack share the same chef repository, you won't be able to use the community NGiNX cookbook as there's already one with the same name.

**Comment by estahn** [comment]
I assume you won't be the only one with that issue. We could define a new proxy type `nginx_opsworks` and run OpsWorks specific code if that helps to reduce code on your end.

``` ruby
node['thumbor']['proxy']['type'] = 'nginx_opsworks'
```

Thoughts?

**Comment by yogin** [comment]
That's actually a good idea, and you can pretty much just reuse the recipe I pasted above, and _it should just work_

I can probably put a PR together later this week if you want

**Comment by estahn** [comment]
That would be great. I created a separate issue (#12). I'll merge as soon as it's available.

**Comment by jandillmann** [comment]
How can I use a custom configuration (e.g. using a secret and disabling unsafe mode) on OpsWorks?
Adding the example JSON from the README.md to the stack configuration results in an error (run_list must not be specified in two places), and when I remove the run_list key, the custom attributes get ignored (unsafe mode is enabled and the security key is not set).
